/**
 * PR Creator Service - Phase 4
 * Creates GitHub pull requests with generated code
 */

import { 
  parseRepoUrl, 
  createBranch, 
  commitFiles, 
  createPullRequest,
  getDefaultBranch,
  checkWriteAccess
} from './githubApiClient.js';
import { getPRDescriptionPrompt } from '../utils/promptTemplates.js';
import { callBobForPRDescription } from './bobApiClient.js';

/**
 * Generate a unique branch name
 * @param {string} prefix - Branch name prefix
 * @returns {string} Unique branch name
 */
function generateBranchName(prefix = 'spectropr') {
  const timestamp = Date.now();
  const random = Math.random().toString(36).substring(2, 8);
  return `${prefix}-${timestamp}-${random}`;
}

/**
 * Generate PR title from specification
 * @param {string} specification - User specification
 * @returns {string} PR title
 */
function generatePRTitle(specification) {
  // Extract first line or first sentence as title
  const firstLine = specification.split('\n')[0].trim();
  const maxLength = 72;
  
  if (firstLine.length <= maxLength) {
    return firstLine;
  }
  
  // Truncate and add ellipsis
  return firstLine.substring(0, maxLength - 3) + '...';
}

/**
 * Generate PR description using Bob API
 * @param {string} specification - Original specification
 * @param {Array<Object>} files - Generated files
 * @returns {Promise<string>} PR description
 */
async function generatePRDescription(specification, files) {
  try {
    console.log('[PR Creator] Generating PR description...');
    
    const prompt = getPRDescriptionPrompt(specification, files);
    const description = await callBobForPRDescription(prompt);
    
    return description;
  } catch (error) {
    console.error('[PR Creator] Error generating PR description:', error.message);
    
    // Fallback to basic description
    return `## Changes\n\n${specification}\n\n## Files Modified\n\n${
      files.map(f => `- ${f.path}`).join('\n')
    }\n\n---\n*Generated by SpecToPR*`;
  }
}

/**
 * Create a pull request with generated code
 * 
 * @param {Object} params - PR creation parameters
 * @param {string} params.repoUrl - GitHub repository URL
 * @param {string} params.specification - User specification
 * @param {Array<Object>} params.files - Generated files [{path, content, explanation}]
 * @param {string} [params.baseBranch] - Base branch (default: repo default)
 * @param {string} [params.branchPrefix='spectropr'] - Branch name prefix
 * @returns {Promise<Object>} PR creation result
 */
export async function createPR(params) {
  const {
    repoUrl,
    specification,
    files,
    baseBranch: providedBaseBranch,
    branchPrefix = 'spectropr'
  } = params;

  try {
    console.log('[PR Creator] Starting PR creation process...');
    
    // Parse repository URL
    const { owner, repo } = parseRepoUrl(repoUrl);
    console.log(`[PR Creator] Repository: ${owner}/${repo}`);

    // Check write access
    const hasAccess = await checkWriteAccess(owner, repo);
    if (!hasAccess) {
      throw new Error('No write access to repository. Check GITHUB_TOKEN permissions.');
    }

    // Get base branch
    const baseBranch = providedBaseBranch || await getDefaultBranch(owner, repo);
    console.log(`[PR Creator] Base branch: ${baseBranch}`);

    // Generate unique branch name
    const newBranch = generateBranchName(branchPrefix);
    console.log(`[PR Creator] New branch: ${newBranch}`);

    // Create branch
    await createBranch(owner, repo, newBranch, baseBranch);

    // Prepare commit message
    const commitMessage = generatePRTitle(specification);

    // Commit files to new branch
    console.log(`[PR Creator] Committing ${files.length} files...`);
    const commitSha = await commitFiles(owner, repo, newBranch, files, commitMessage);

    // Generate PR description
    const prDescription = await generatePRDescription(specification, files);

    // Create pull request
    const prTitle = generatePRTitle(specification);
    const pr = await createPullRequest(
      owner,
      repo,
      prTitle,
      newBranch,
      baseBranch,
      prDescription
    );

    console.log('[PR Creator] Pull request created successfully');

    return {
      success: true,
      prUrl: pr.url,
      prNumber: pr.number,
      branch: newBranch,
      baseBranch,
      commitSha,
      filesCommitted: files.length,
      prDescription
    };

  } catch (error) {
    console.error('[PR Creator] Error creating PR:', error.message);
    throw new Error(`Failed to create pull request: ${error.message}`);
  }
}

/**
 * Validate PR creation parameters
 * @param {Object} params - Parameters to validate
 * @returns {Object} Validation result
 */
export function validatePRParams(params) {
  const errors = [];

  if (!params.repoUrl) {
    errors.push('repoUrl is required');
  }

  if (!params.specification || params.specification.trim().length === 0) {
    errors.push('specification is required and cannot be empty');
  }

  if (!params.files || !Array.isArray(params.files) || params.files.length === 0) {
    errors.push('files array is required and cannot be empty');
  }

  if (params.files) {
    params.files.forEach((file, index) => {
      if (!file.path) {
        errors.push(`File at index ${index} is missing path`);
      }
      if (file.content === undefined) {
        errors.push(`File at index ${index} is missing content`);
      }
    });
  }

  return {
    valid: errors.length === 0,
    errors
  };
}

/**
 * Create PR with rollback capability
 * If PR creation fails after branch creation, attempts to delete the branch
 * 
 * @param {Object} params - PR creation parameters
 * @returns {Promise<Object>} PR creation result
 */
export async function createPRWithRollback(params) {
  let branchCreated = false;
  let branchName = null;
  let owner = null;
  let repo = null;

  try {
    // Validate parameters
    const validation = validatePRParams(params);
    if (!validation.valid) {
      throw new Error(`Invalid parameters: ${validation.errors.join(', ')}`);
    }

    // Parse repo info for potential rollback
    const parsed = parseRepoUrl(params.repoUrl);
    owner = parsed.owner;
    repo = parsed.repo;

    // Attempt to create PR
    const result = await createPR(params);
    branchCreated = true;
    branchName = result.branch;

    return result;

  } catch (error) {
    // If branch was created but PR failed, attempt rollback
    if (branchCreated && branchName && owner && repo) {
      console.log(`[PR Creator] Attempting to rollback branch: ${branchName}`);
      try {
        // Note: GitHub API doesn't easily support branch deletion via Octokit
        // This would require additional implementation
        console.warn('[PR Creator] Branch rollback not implemented - manual cleanup may be needed');
      } catch (rollbackError) {
        console.error('[PR Creator] Rollback failed:', rollbackError.message);
      }
    }

    throw error;
  }
}

/**
 * Get PR creation summary for logging
 * @param {Object} result - PR creation result
 * @returns {Object} Summary object
 */
export function getPRSummary(result) {
  return {
    status: result.success ? 'success' : 'failed',
    prUrl: result.prUrl,
    prNumber: result.prNumber,
    branch: result.branch,
    filesCommitted: result.filesCommitted,
    timestamp: new Date().toISOString()
  };
}

// Made with Bob
